typings v2
TalAter/annyang pull request #304
Opened 2017-08-23 16:51 UTC by hisham

Bundling types as discussed in https://github.com/TalAter/annyang/pull/197. 

## Description
- Added typescript definitions in types/index.d.ts
- Also added typescript definition test files along with necessary files to run the tests
- Followed instructions at https://github.com/Microsoft/dtslint to do this and using dtslint for testing
- Added 'types-test' command in package.json to run it, and added it to the grunt tasks

## Motivation and Context
So that annyang can be easily used in typescript apps. See https://github.com/TalAter/annyang/pull/197.

## How Has This Been Tested?
- Added dtslint tests
- Tested using command line 'npm run types-test'
- And tested this latest package with my own typescript-based angular project - everything worked

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2017-08-23 20:33 UTC, TalAter commented
Wow, this is a model pull request. You have thought of everything.

Give me some time to go over it, I am still new to the world of TypeScript.

2017-08-23 20:37 UTC, hisham commented
thanks :)
ᐧ

On Wed, Aug 23, 2017 at 2:34 PM, Tal Ater <notifications@github.com> wrote:

> Wow, this is a model pull request. You have thought of everything.
>
> Give me some time to go over it, I am still new to the world of TypeScript.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TalAter/annyang/pull/304#issuecomment-324454269>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAE_vcySWS_Ioe0cQ1_mR0BpAcluXlnIks5sbIy6gaJpZM4PAS8C>
> .
>

2017-08-23 21:45 UTC, TalAter requested changes

2017-08-23 21:45 UTC, TalAter commented on types/index.d.ts
> +    removeCommands(command: string[]): void;
Does `removeCommands()` need to be repeated twice?

Could we do something like:
`removeCommands(command?: string | string[]): void;`

I am unsure of the syntax, so consider my suggestion pseudo code.

2017-08-23 21:45 UTC, TalAter commented on types/index.d.ts
> +export interface Annyang {
Is export interface the correct way to do this?
Looking at this [example](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html), and at the footnote [Preventing Name Conflicts](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html), it looks like we might actually want to define a namespace annyang.

Am I understanding this wrong?

2017-08-24 19:09 UTC, hisham commented
good points on both. now fixed.

2017-09-18 17:42 UTC, hisham commented
So will this be merged? Would hate to have my pull request go to waste...

2017-09-22 09:08 UTC, TalAter commented
Definitely! I am just not very experienced with TypeScript, and so asking for help with making sure I don't miss anything.

My apologies for it taking so long!

2019-04-04 07:42 UTC, anoblet commented
This would be useful for me.

2026-03-11 07:40 UTC, TalAter commented
Thank you for this PR! TypeScript types are now fully bundled with annyang starting in **v3.0.0** — the entire library has been rewritten in TypeScript with strict mode.

See the release: https://github.com/TalAter/annyang/releases/tag/v3.0.0

2026-03-11 07:41 UTC, closed without merging